controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Image;
use app\models\Login;
use app\models\Register;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\gii\Module;
use yii\web\Controller;
use yii\filters\VerbFilter;
//use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'denyCallback' => function ($rule, $action) {
                    return $this->goHome();
                },
                'only' => ['login', 'logout', 'register', 'users'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login', 'register'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['logout', 'users'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }
    /**
     * Index page
     * @return array images
     */
    public function actionIndex()
    {
        $image_model = new Image();
        $images = $image_model->getAll();

        return $this->render('index', ['images' => $images]);
    }

    /**
     * Show register page and performs registration
     * @return object| /and redirect to index page
     */
    public function actionRegister()
    {
        $model = new Register();

        if(isset($_POST['Register'])){
            $model->attributes = Yii::$app->request->post('Register');
            if($model->validate()){
                $model->register();
                return $this->goHome();
            }
        }

        return $this->render('register', ['model' => $model]);
    }
    public function actions()
    {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
            ],
        ];
    }

    /**
     * Login Method
     * @return object| login user data and redirect to index page
     */
    public function actionLogin()
    {
        $login_model = new Login();

        if(Yii::$app->request->post('Login')){
            $login_model->attributes = Yii::$app->request->post('Login');

            if($login_model->validate()){
                Yii::$app->user->login($login_model->getUser());
                return $this->goHome();
            }
        }

        return $this->render('login', ['login_model' => $login_model]);
    }

    /**
     * Logout method
     * @redirect to index page
     */
    public function actionLogout()
    {
        if(!Yii::$app->user->isGuest){
            Yii::$app->user->logout();
            return $this->redirect(['login']);
        }
    }


    /**
     * Show all users
     * @return array all users
     */
    public function actionUsers()
    {
//        if(Yii::$app->user->isGuest){
//            return $this->goHome();
//        }

        $user_model = new User();
        $users = $user_model->getAll();

        return $this->render('users', ['users' => $users]);
    }

    /**
     * Home page
     * @return array from user data
     */
    public function actionHome()
    {
        $user_model = new User();
        $user = $user_model->findIdentity(Yii::$app->user->id);

        return $this->render('home', ['user' => $user]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>


    <?php $this->head() ?>
    <?= Html::jsFile('@web/js/jquery-1.3.2.min.js') ?>
    <script type="text/javascript">

    </script>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Images Blog',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Index', 'url' => ['/site/index']],
            ['label' => 'Users', 'url' => ['/site/users']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Register', 'url' => ['/site/register']]
            ) : (
                ['label' => 'Home', 'url' => ['/site/home']]
            ),
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'navbar-form'])
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Images Blog <?= date('Y') ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>